### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Romero027** [Romero027/bookinfo-grpc#1]
- [ ] Add persistent storage for each service
- [ ] Enhance the productpage.html
- [ ] Add more products on initialization 
- [ ] Add support for kiali
- [ ] Add support for grafana
